### ISSUE TITLE
`xatimesun` in generator-gt-desc, but not analyser-gt-desc

### ISSUE THREAD

**Issue by reynoldsnlp** [giellalt/lang-kek#6]
`make check` fails on analyzing `xatimesun` with `analyser-gt-desc.hfstol`:

```
[1/1][FAIL] xatinmesun => Missing results: mesun+V+RECPST+TR+2SN.OBJ+1SN.SBJ
```

This form is in `generator-gt-desc.hfstol`:
```
$ echo mesun+V+RECPST+TR+2SN.OBJ+1SN.SBJ | hfst-lookup src/generator-gt-desc.hfstol
> mesun+V+RECPST+TR+2SN.OBJ+1SN.SBJ	xatinmesun	0.000000
```

I tried looking for a different surface form using the following commands:

```
$ hfst-fst2strings -X obey-flags src/analyser-gt-desc.hfstol | grep mesun+V+RECPST+TR+2SN.OBJ+1SN.SBJ
Xatinmesun:mesun+V+RECPST+TR+2SN.OBJ+1SN.SBJ
xatinmesun:mesun+V+RECPST+TR+2SN.OBJ+1SN.SBJ
```

It found `xatinmesun` as the surface form of that reading in the very analyzer that failed the test. I then assumed that the characters might not actually be ASCII or something like that, so I copied and pasted the surface form from that output into hfst-lookup, and it failed.

* `hfst-lookup` might be treating flags differently from `hfst-fst2strings` by default??

**Comment by xoyito** [comment]
The issue was with TWOLC syntax
