### ISSUE TITLE
`lexd` isn't found by CI

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-kek#9]
It seems the GitHub Action runner isn't able to find `lexd`, despite it being installed. At least `https://apertium.projectjj.com/apt/install-nightly.sh` is run as part of the **Install dev dependencies** CI step.

See https://github.com/giellalt/lang-kek/actions/runs/10697405966/job/29654523834 for an example of a failure.

`lang-kek` should otherwise build fine, as demonstrated by https://apertium.projectjj.com/apt/logs/giella-kek/build.log.

@flammie could you have a look?

**Comment by flammie** [comment]
lexd installation was dependent on apertium setting in divvun ci actions
